sonar.projectKey=stockpro-backend
sonar.projectName=StockPro Backend
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.inclusions=**/src/main/java/**/*.java
sonar.test.inclusions=**/src/test/java/**/*.java
sonar.exclusions=**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd,**/.DS_Store
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
